### ISSUE TITLE
Switch to Phantomas 2.0 when it's ready

### ISSUE THREAD

**Issue by gmetais** [YellowLabTools/YellowLabTools#278]
The next Phantomas version is under heavy development, with a Chrome Headless engine instead of PhantomJS.

**Comment by gmetais** [comment]
Phantomas v2 is not ready yet, but I started to implement it on branch [ylt-v2](https://github.com/gmetais/YellowLabTools/tree/ylt-v2).

A few notes:
- everything is broken for the moment, no need to try!
- I removed compatibility with node v6 (now >= 8)
- I removed JS profiling, JS timeline and Scroll related metrics (see #279)
- there are still a bunch of tests failing
- Phantomas v2 does not handle screenshots yet

**Comment by macbre** [comment]
See https://github.com/macbre/phantomas/issues/707

**Comment by macbre** [comment]
@gmetais - you can try to install phantomas from the v2 feature branch:

```
npm install --save macbre/phantomas@phantomas-v2
```

**Comment by gmetais** [comment]
👏👏👏 for the huge work!
I'm currently on holidays with the whole family, but I can't wait to test!

**Comment by macbre** [comment]
Enjoy your holidays :slightly_smiling_face:

**Comment by gmetais** [comment]
Switching to v2 is in progress!
The new engine works great and every metrics in use in YLT seem to respond accurately 💪

**Comment by macbre** [comment]
@gmetais - these are great news!

**Comment by gmetais** [comment]
@macbre I've tested something like 20 different websites and I've only had a problem with one: `https://www.airfrance.fr/`

Error: Navigation failed because browser has disconnected!
    at /Users/gaelmetais/Documents/GitHub/phantomas/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:51:147
    at /Users/gaelmetais/Documents/GitHub/phantomas/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:47:62
    at Array.map (<anonymous>)
    at Object.emit (/Users/gaelmetais/Documents/GitHub/phantomas/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:47:43)
    at CDPSession.emit (/Users/gaelmetais/Documents/GitHub/phantomas/node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
    at CDPSession._onClosed (/Users/gaelmetais/Documents/GitHub/phantomas/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:247:14)
    at Connection._onClose (/Users/gaelmetais/Documents/GitHub/phantomas/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:128:21)
    at WebSocket.<anonymous> (/Users/gaelmetais/Documents/GitHub/phantomas/node_modules/puppeteer/lib/cjs/puppeteer/common/WebSocketTransport.js:17:30)
    at WebSocket.onClose (/Users/gaelmetais/Documents/GitHub/phantomas/node_modules/ws/lib/event-target.js:129:16)
    at WebSocket.emit (events.js:314:20)

**Comment by macbre** [comment]
@gmetais - yes, please.

**Comment by gmetais** [comment]
Done with #322.
