### ISSUE TITLE
building on Ubuntu 20.10?

### ISSUE THREAD

**Issue by platipusica** [YellowLabTools/YellowLabTools#324]
Hi guys,

not having fun with Ubuntu tho, any suggestions? Failing on imagemin-jpegtran - cannot find module. Tried everything I could.

Other that that, awesome stuff you've built, thanks a million!

**Comment by platipusica** [comment]
Anyone?

If not proven on Ubuntu 20.10 can I get the distro version which is proven to work?

**Comment by ousamabenyounes** [comment]
Hi,

I should recommend you to use docker image it is really easy

docker run --privileged -p 8383:8383    ousamabenyounes/yellowlabtools
And then open http://localhost:8383/ on your web Browser.

=> https://github.com/ousamabenyounes/docker-yellowlabtools



Cordialement,

Ben Younes Ousama.

<http://yellowlab.tools>




Le mar. 19 janv. 2021 à 02:11, platipusica <notifications@github.com> a
écrit :

**Comment by platipusica** [comment]
Hi, 

thanks! 
It can't connect to 127.0.0.1:8080 inside the VM though:

```
Launching test fv2l80qotc on http://127.0.0.1:8080/
Error: net::ERR_CONNECTION_REFUSED at http://127.0.0.1:8080/
    at navigate (/usr/src/ylt/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:115:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async FrameManager.navigateFrame (/usr/src/ylt/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:90:21)
    at async Frame.goto (/usr/src/ylt/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:417:16)
    at async Page.goto (/usr/src/ylt/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:784:16)
    at async /usr/src/ylt/node_modules/phantomas/lib/browser.js:273:7
Test failed for URL: http://127.0.0.1:8080/
Phantomas failed: net::ERR_CONNECTION_REFUSED at http://127.0.0.1:8080/
```
Any idea?
Running as root and can connect with "curl http://127.0.0.1:8080"

Cheers
