### ISSUE TITLE
Ubuntu 22.04 install, would this go smoother if I use ubuntu 20.04 or 18.04?

### ISSUE THREAD

**Issue by Jieiku** [YellowLabTools/YellowLabTools#368]
Got it up and running: https://github.com/YellowLabTools/YellowLabTools-server/issues/2

**Comment by Jieiku** [comment]
Ubuntu 20.04 did get farther:

```sh
git clone https://github.com/YellowLabTools/YellowLabTools-server.git YellowLabTools
cd YellowLabTools
npm install

node bin/server.js

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'yellowlabtools'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/YellowLabTools/lib/controllers/apiController.js:4:27)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by Jieiku** [comment]
got it installed on ubuntu 20.04:

apt install git npm
git clone https://github.com/YellowLabTools/YellowLabTools
cd YellowLabTools
npm install -g yellowlabtools
cd..
git clone https://github.com/YellowLabTools/YellowLabTools-server
cd YellowLabTools-server
npm install
node bin/server.js

http://localhost:8383

the page comes up, but errors out, hoping I can find the answer in the logs, will report back if I do:

![2022-08-20_22-25-09](https://user-images.githubusercontent.com/106644/185776848-013e780b-da22-4fba-85e3-01df5796d71a.png)

**Comment by Jieiku** [comment]
I think my issues now stem back to the version of node/npm would be great if a last workable version was listed. I dont use docker but I guess I will have to mess around with it to see what versions are in use on it.
