### ISSUE TITLE
Private instance instructions fail

### ISSUE THREAD

**Issue by mikeott** [YellowLabTools/YellowLabTools#377]
Following the [private instance installation guide](https://github.com/YellowLabTools/YellowLabTools/wiki/Install-your-private-server), I get this error as soon as I run **npm install**:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: yellowlabtools-server@1.0.0
npm ERR! Found: grunt@1.0.4
npm ERR! node_modules/grunt
npm ERR!   dev grunt@"~1.0.4" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer grunt@"~0.4.1" from grunt-inline-angular-templates@0.1.5
npm ERR! node_modules/grunt-inline-angular-templates
npm ERR!   dev grunt-inline-angular-templates@"~0.1.5" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

If I retry using **--force** it gets further:

```
pm WARN using --force Recommended protections disabled.
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: grunt-inline-angular-templates@0.1.5
npm WARN Found: grunt@1.0.4
npm WARN node_modules/grunt
npm WARN   dev grunt@"~1.0.4" from the root project
npm WARN   6 more (grunt-contrib-clean, grunt-contrib-concat, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer grunt@"~0.4.1" from grunt-inline-angular-templates@0.1.5
npm WARN node_modules/grunt-inline-angular-templates
npm WARN   dev grunt-inline-angular-templates@"~0.1.5" from the root project
npm WARN 
npm WARN Conflicting peer dependency: grunt@0.4.5
npm WARN node_modules/grunt
npm WARN   peer grunt@"~0.4.1" from grunt-inline-angular-templates@0.1.5
npm WARN   node_modules/grunt-inline-angular-templates
npm WARN     dev grunt-inline-angular-templates@"~0.1.5" from the root project
npm WARN deprecated grunt-filerev@2.3.1: Deprecated
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated angular-route@1.7.7: For the actively supported Angular, see https://www.npmjs.com/package/@angular/core. AngularJS support has officially ended. For extended AngularJS support options, see https://goo.gle/angularjs-path-forward.
npm WARN deprecated angular-sanitize@1.7.7: For the actively supported Angular, see https://www.npmjs.com/package/@angular/core. AngularJS support has officially ended. For extended AngularJS support options, see https://goo.gle/angularjs-path-forward.
npm WARN deprecated angular-resource@1.7.7: For the actively supported Angular, see https://www.npmjs.com/package/@angular/core. AngularJS support has officially ended. For extended AngularJS support options, see https://goo.gle/angularjs-path-forward.
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated angular-animate@1.7.7: For the actively supported Angular, see https://www.npmjs.com/package/@angular/core. AngularJS support has officially ended. For extended AngularJS support options, see https://goo.gle/angularjs-path-forward.
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated @babel/polyfill@7.12.1: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
npm WARN deprecated angular@1.7.7: For the actively supported Angular, see https://www.npmjs.com/package/@angular/core. AngularJS support has officially ended. For extended AngularJS support options, see https://goo.gle/angularjs-path-forward.
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

added 645 packages, and audited 647 packages in 35s

35 packages are looking for funding
  run `npm fund` for details

31 vulnerabilities (17 high, 14 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
```

And if I ignore that and run the **node bin/server.js** command I get this:

```
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'yellowlabtools'
Require stack:
- /home/storm/YellowLabTools-server/lib/controllers/apiController.js
- /home/storm/YellowLabTools-server/bin/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/storm/YellowLabTools-server/lib/controllers/apiController.js:4:27)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/storm/YellowLabTools-server/lib/controllers/apiController.js',
    '/home/storm/YellowLabTools-server/bin/server.js'
  ]
}
```

Attempting to install on a fresh instance of Ubuntu 22.04 (as an inexperienced Ubuntu user).

**Comment by gmetais** [comment]
Hmm... it looks like it's a little messed up. Sorry about that, I need to do some clean up soon.

Editing package.json and replacing `"yellowlabtools": "file:../YellowLabTools"` by `"yellowlabtools": "2.2.0"` should help.

**Comment by mikeott** [comment]
No worries @gmetais, and yes that edit to package.json did fix it. Consider the issue closed from my perspective.
