### ISSUE TITLE
Private instance always fails to parse the CSS

### ISSUE THREAD

**Issue by mikeott** [YellowLabTools/YellowLabTools#378]
Any site I test reports a **CSS syntax error**, which goes on to explain:

_"Yellow Lab Tools failed to parse a CSS file. I doubt the problem comes from the css parser."_

But when I run the same sites through [the public facing site](https://yellowlab.tools/), the CSS is read without any dramas.

**Comment by gmetais** [comment]
Do you see any errors in your terminal when you launch the server like that? 
`DEBUG=analyze-css:* node bin/server.js`

**Comment by mikeott** [comment]
Negative. The terminal says "Listening on port 8383" and that's all. It only updates when running a test. Example:

`Launching test ghw0bjpzof on https://rocketapps.com.au/`

**Comment by mikeott** [comment]
Yes, lots of errors:

```
^[[ALaunching test ghw0e1fvgl on https://rocketapps.com.au/
  analyze-css:rules Rules to be loaded: base64, bodySelectors, childSelectors, colors, comments, complex, duplicated, emptyRules, expressions, ieFixes, import, important, length, mediaQueries, minified, multiClassesSelectors, parsingErrors, prefixes, propertyResets, qualified, specificity, stats +0ms
  analyze-css:rules "base64" loaded: Reports on base64-encoded images +2ms
  analyze-css:rules "bodySelectors" loaded: Reports redundant body selectors +1ms
  analyze-css:rules Rules to be loaded: base64, bodySelectors, childSelectors, colors, comments, complex, duplicated, emptyRules, expressions, ieFixes, import, important, length, mediaQueries, minified, multiClassesSelectors, parsingErrors, prefixes, propertyResets, qualified, specificity, stats +0ms
  analyze-css:rules "base64" loaded: Reports on base64-encoded images +0ms
  analyze-css:rules "bodySelectors" loaded: Reports redundant body selectors +0ms
  analyze-css:rules Rules to be loaded: base64, bodySelectors, childSelectors, colors, comments, complex, duplicated, emptyRules, expressions, ieFixes, import, important, length, mediaQueries, minified, multiClassesSelectors, parsingErrors, prefixes, propertyResets, qualified, specificity, stats +0ms
  analyze-css:rules "base64" loaded: Reports on base64-encoded images +0ms
  analyze-css:rules "bodySelectors" loaded: Reports redundant body selectors +1ms
  analyze-css:rules Rules to be loaded: base64, bodySelectors, childSelectors, colors, comments, complex, duplicated, emptyRules, expressions, ieFixes, import, important, length, mediaQueries, minified, multiClassesSelectors, parsingErrors, prefixes, propertyResets, qualified, specificity, stats +0ms
  analyze-css:rules "base64" loaded: Reports on base64-encoded images +1ms
  analyze-css:rules "bodySelectors" loaded: Reports redundant body selectors +0ms
  analyze-css:rules Rules to be loaded: base64, bodySelectors, childSelectors, colors, comments, complex, duplicated, emptyRules, expressions, ieFixes, import, important, length, mediaQueries, minified, multiClassesSelectors, parsingErrors, prefixes, propertyResets, qualified, specificity, stats +0ms
  analyze-css:rules "base64" loaded: Reports on base64-encoded images +0ms
  analyze-css:rules "bodySelectors" loaded: Reports redundant body selectors +0ms
  analyze-css:rules Rules to be loaded: base64, bodySelectors, childSelectors, colors, comments, complex, duplicated, emptyRules, expressions, ieFixes, import, important, length, mediaQueries, minified, multiClassesSelectors, parsingErrors, prefixes, propertyResets, qualified, specificity, stats +0ms
  analyze-css:rules "base64" loaded: Reports on base64-encoded images +0ms
  analyze-css:rules "bodySelectors" loaded: Reports redundant body selectors +0ms
  analyze-css:rules Rules to be loaded: base64, bodySelectors, childSelectors, colors, comments, complex, duplicated, emptyRules, expressions, ieFixes, import, important, length, mediaQueries, minified, multiClassesSelectors, parsingErrors, prefixes, propertyResets, qualified, specificity, stats +0ms
  analyze-css:rules "base64" loaded: Reports on base64-encoded images +0ms
  analyze-css:rules "bodySelectors" loaded: Reports redundant body selectors +0ms
  analyze-css:rules Rules to be loaded: base64, bodySelectors, childSelectors, colors, comments, complex, duplicated, emptyRules, expressions, ieFixes, import, important, length, mediaQueries, minified, multiClassesSelectors, parsingErrors, prefixes, propertyResets, qualified, specificity, stats +0ms
  analyze-css:rules "base64" loaded: Reports on base64-encoded images +0ms
  analyze-css:rules "bodySelectors" loaded: Reports redundant body selectors +0ms
  analyze-css:rules Rules to be loaded: base64, bodySelectors, childSelectors, colors, comments, complex, duplicated, emptyRules, expressions, ieFixes, import, important, length, mediaQueries, minified, multiClassesSelectors, parsingErrors, prefixes, propertyResets, qualified, specificity, stats +0ms
  analyze-css:rules "base64" loaded: Reports on base64-encoded images +0ms
  analyze-css:rules "bodySelectors" loaded: Reports redundant body selectors +0ms
  analyze-css:rules Rules to be loaded: base64, bodySelectors, childSelectors, colors, comments, complex, duplicated, emptyRules, expressions, ieFixes, import, important, length, mediaQueries, minified, multiClassesSelectors, parsingErrors, prefixes, propertyResets, qualified, specificity, stats +0ms
  analyze-css:rules "base64" loaded: Reports on base64-encoded images +0ms
  analyze-css:rules "bodySelectors" loaded: Reports redundant body selectors +0ms
  analyze-css:rules Rules to be loaded: base64, bodySelectors, childSelectors, colors, comments, complex, duplicated, emptyRules, expressions, ieFixes, import, important, length, mediaQueries, minified, multiClassesSelectors, parsingErrors, prefixes, propertyResets, qualified, specificity, stats +0ms
  analyze-css:rules "base64" loaded: Reports on base64-encoded images +0ms
  analyze-css:rules "bodySelectors" loaded: Reports redundant body selectors +0ms
  analyze-css:rules Rules to be loaded: base64, bodySelectors, childSelectors, colors, comments, complex, duplicated, emptyRules, expressions, ieFixes, import, important, length, mediaQueries, minified, multiClassesSelectors, parsingErrors, prefixes, propertyResets, qualified, specificity, stats +0ms
  analyze-css:rules "base64" loaded: Reports on base64-encoded images +0ms
  analyze-css:rules "bodySelectors" loaded: Reports redundant body selectors +0ms
  analyze-css:rules Rules to be loaded: base64, bodySelectors, childSelectors, colors, comments, complex, duplicated, emptyRules, expressions, ieFixes, import, important, length, mediaQueries, minified, multiClassesSelectors, parsingErrors, prefixes, propertyResets, qualified, specificity, stats +0ms
  analyze-css:rules "base64" loaded: Reports on base64-encoded images +0ms
  analyze-css:rules "bodySelectors" loaded: Reports redundant body selectors +1ms
  analyze-css:rules Rules to be loaded: base64, bodySelectors, childSelectors, colors, comments, complex, duplicated, emptyRules, expressions, ieFixes, import, important, length, mediaQueries, minified, multiClassesSelectors, parsingErrors, prefixes, propertyResets, qualified, specificity, stats +0ms
  analyze-css:rules "base64" loaded: Reports on base64-encoded images +0ms
  analyze-css:rules "bodySelectors" loaded: Reports redundant body selectors +0ms
  analyze-css:rules Rules to be loaded: base64, bodySelectors, childSelectors, colors, comments, complex, duplicated, emptyRules, expressions, ieFixes, import, important, length, mediaQueries, minified, multiClassesSelectors, parsingErrors, prefixes, propertyResets, qualified, specificity, stats +0ms
  analyze-css:rules "base64" loaded: Reports on base64-encoded images +0ms
  analyze-css:rules "bodySelectors" loaded: Reports redundant body selectors +1ms
```

**Comment by mikeott** [comment]
Yes:

```
Launching test ghw0hskh17 on https://michaelott.id.au/
  analyze-css:rules Rules to be loaded: base64, bodySelectors, childSelectors, colors, comments, complex, duplicated, emptyRules, expressions, ieFixes, import, important, length, mediaQueries, minified, multiClassesSelectors, parsingErrors, prefixes, propertyResets, qualified, specificity, stats +0ms
  analyze-css:rules "base64" loaded: Reports on base64-encoded images +2ms
  analyze-css:rules "bodySelectors" loaded: Reports redundant body selectors +2ms
  analyze-css:rules Rules to be loaded: base64, bodySelectors, childSelectors, colors, comments, complex, duplicated, emptyRules, expressions, ieFixes, import, important, length, mediaQueries, minified, multiClassesSelectors, parsingErrors, prefixes, propertyResets, qualified, specificity, stats +0ms
  analyze-css:rules "base64" loaded: Reports on base64-encoded images +1ms
  analyze-css:rules "bodySelectors" loaded: Reports redundant body selectors +0ms
```

..and scores an F.

But the public facing site actually gives me a score (A).

**Comment by gmetais** [comment]
This is not actual errors, this is normal logs, but it is quite strange if you only get those.

Can you please try to install analyze-css (`npm install -g analyze-css`) and test a CSS file independently?

`analyze-css --url https://www.domain.com/styles.css`

**Comment by mikeott** [comment]
No worries. I installed that module, and got the same error when testing on several different stylesheets.

Example...

`analyze-css --url https://rocketapps.com.au/wp-includes/css/dist/block-library/style.min.css`

...returns this error: 

`SyntaxError: Unexpected token '.'`

**Comment by gmetais** [comment]
I see that the analyze-css version currently in use in YLT is not compatible with the `:where()` keyword.
I've just tried the latest version of analyze-css on my computer and it works.

I'll keep this ticket open and update the phantomas package (which summons analyze-css) when I have a moment.

In the meanwhile, you can edit YLT's package.json and set phantomas to its latest version (2.5.0), then:

```
rm -rf node_modules/phantomas
rm -rf node_modules/analyze-css
npm install phantomas
```

Let me know if you have an issue.

**Comment by mikeott** [comment]
This is what my package.json looks like:

```
{
  "name": "yellowlabtools-server",
  "version": "1.0.0",
  "description": "The web server of YellowLabTools, and online tool that audits a webpage for performance and front-end quality issues",
  "license": "GPL-2.0",
  "author": {
    "name": "Gaël Métais",
    "email": "gael@gaelmetais.com",
    "url": "https://www.gaelmetais.com"
  },
  "repository": {
    "type": "git",
    "url": "git://github.com/YellowLabTools/YellowLabTools-server.git"
  },
  "bin": {
    "server": "./bin/server.js"
  },
  "engines": {
    "node": ">= 12.0"
  },
  "dependencies": {
    "angular": "1.7.7",
    "angular-animate": "1.7.7",
    "angular-chart.js": "1.1.1",
    "angular-local-storage": "0.7.1",
    "angular-resource": "1.7.7",
    "angular-route": "1.7.7",
    "angular-sanitize": "1.7.7",
    "body-parser": "1.18.3",
    "chart.js": "2.7.3",
    "compression": "1.7.3",
    "cors": "2.8.5",
    "debug": "4.1.1",
    "easyxml": "2.0.1",
    "ejs": "2.6.1",
    "express": "4.16.4",
    "fontkit": "1.7.8",
    "q": "1.5.1",
    "rimraf": "2.6.3",
    "temporary": "0.0.8",
    "yellowlabtools": "2.2.0"
  },
  "devDependencies": {
    "chai": "~4.2.0",
    "grunt": "~1.0.4",
    "grunt-contrib-clean": "~2.0.0",
    "grunt-contrib-concat": "~1.0.1",
    "grunt-contrib-copy": "~1.0.0",
    "grunt-contrib-cssmin": "~3.0.0",
    "grunt-contrib-htmlmin": "~3.0.0",
    "grunt-contrib-jshint": "~2.0.0",
    "grunt-contrib-less": "~2.0.0",
    "grunt-contrib-uglify": "~4.0.0",
    "grunt-contrib-watch": "~1.1.0",
    "grunt-env": "~0.4.4",
    "grunt-filerev": "~2.3.1",
    "grunt-inline-angular-templates": "~0.1.5",
    "grunt-mocha-test": "~0.13.3",
    "grunt-parallel": "~0.5.1",
    "grunt-usemin": "~3.1.1",
    "jimp": "0.6.0",
    "matchdep": "~2.0.0",
    "mocha": "~5.2.0",
    "sinon": "~7.2.3",
    "sinon-chai": "~3.3.0"
  },
  "scripts": {
    "test": "todo",
    "build": "grunt build"
  },
  "keywords": [
    "performance",
    "metrics",
    "webperf",
    "pagespeed",
    "budget",
    "phantomas"
  ]
}
```

So I'm guessing I need to add `"phantomas": "2.5.0"` after the line `"fontkit": "1.7.8"` ?

If so, I tried that anyway and received this:

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'analyze-css@2.1.81',
npm WARN EBADENGINE   required: { node: '^14.0.0 || >=16.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'commander@10.0.0',
npm WARN EBADENGINE   required: { node: '>=14' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'puppeteer@14.4.1',
npm WARN EBADENGINE   required: { node: '>=14.1.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'phantomas@2.4.0',
npm WARN EBADENGINE   required: { node: '>=14.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'phantomas@2.5.0',
npm WARN EBADENGINE   required: { node: '>=14.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }

```

If I'm reading that right, my current version of node is `v12.22.9` which is less than the required version (and there are apparently some unsupported engines). But if I attempt to update node it says:

```
nodejs is already the newest version (12.22.9~dfsg-1ubuntu3).
npm is already the newest version (8.5.1~ds-1).
```

**Comment by gmetais** [comment]
Actually the package.json you need to fix is here `node_modules/yellowlabtools/package.json`. Sorry for the wrong information.

Damn node version :) The latest NodeJS version is 18, your computer is telling you lies. There's probably another way to update it. But I'd recommend you to install v14 for YLT.

**Comment by mikeott** [comment]
I managed to download node v14 ([this](https://stackoverflow.com/a/71061274/3256143) was the only guide that actually worked) and I ran the commands as suggested.

I ran the commands you suggested, but `npm install phantomas` eventually threw an error:

```
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm WARN deprecated puppeteer@14.4.1: < 18.1.0 is no longer supported

> ttf2woff2@4.0.1 install /home/stormbox/YellowLabTools-server/node_modules/ttf2woff2
> ((node-gyp configure && node-gyp build) > builderror.log) || (exit 0)


> puppeteer@13.7.0 install /home/stormbox/YellowLabTools-server/node_modules/yellowlabtools/node_modules/puppeteer
> node install.js

Downloading Chromium r982053 - 150.3 Mb [====================] 100% 0.0s 

> puppeteer@14.4.1 install /home/stormbox/YellowLabTools-server/node_modules/puppeteer
> node install.js

Downloading Chromium r1002410 - 149 Mb [====================] 100% 0.0s 

> core-js@2.6.12 postinstall /home/stormbox/YellowLabTools-server/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> jpegoptim-bin@6.0.1 postinstall /home/stormbox/YellowLabTools-server/node_modules/jpegoptim-bin
> node lib/install.js

jpegoptim pre-build test passed successfully

> jpegtran-bin@5.0.2 postinstall /home/stormbox/YellowLabTools-server/node_modules/jpegtran-bin
> node lib/install.js

  ✔ jpegtran pre-build test passed successfully

> optipng-bin@7.0.1 postinstall /home/stormbox/YellowLabTools-server/node_modules/optipng-bin
> node lib/install.js

optipng pre-build test passed successfully
npm WARN notsup Unsupported engine for puppeteer@14.4.1: wanted: {"node":">=14.1.0"} (current: {"node":"14.0.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: puppeteer@14.4.1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ phantomas@2.5.0
added 10 packages from 37 contributors, updated 1169 packages and audited 1180 packages in 89.697s

95 packages are looking for funding
  run `npm fund` for details

found 58 vulnerabilities (3 low, 21 moderate, 27 high, 7 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

```

I think this is saying I actually need node 14.1.0, which I did mange to install (eventually) and confirm.

So running [those three commands](https://github.com/YellowLabTools/YellowLabTools/issues/378#issuecomment-1416836494) again, I now get this error...

```
ERROR: npm v9.4.1 is known not to run on Node.js v14.0.0. You'll need to upgrade
to a newer Node.js version in order to use this version of npm. This version of
npm supports the following node versions: `^14.17.0 || ^16.13.0 || >=18.0.0`. You
can find the latest version at https://nodejs.org/.

ERROR:
/usr/local/lib/node_modules/npm/node_modules/hosted-git-info/lib/index.js:63
  #fill (template, opts) {
        ^

SyntaxError: Unexpected token '('
    at wrapSafe (internal/modules/cjs/loader.js:1101:16)
    at Module._compile (internal/modules/cjs/loader.js:1149:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:8:19)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
```

...which  I guess means I actually need to be running node v14.17.0 at the least. I've updated to that version of node now, ran the commands, and I get this error:

```
npm WARN deprecated puppeteer@14.4.1: < 18.1.0 is no longer supported
npm WARN grunt-inline-angular-templates@0.1.5 requires a peer of grunt@~0.4.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ phantomas@2.5.0
added 10 packages from 37 contributors and audited 1180 packages in 8.304s

94 packages are looking for funding
  run `npm fund` for details

found 58 vulnerabilities (3 low, 21 moderate, 27 high, 7 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

What would you recommend next?

**Comment by gmetais** [comment]
Well, it should work now, doesn't it?

If not, delete the entire node_modules directory, start re-installing, then delete phantomas and analyze-css, and change phantomas version to reinstall the latest.

**Comment by mikeott** [comment]
After going through what I can only describe as command line hell, the CSS appears to give real CSS results now (instead of always an F).

I ended up deleting everything and starting again, trying my best to connect the dots between ambiguous command line error messages and your suggestions. I appeared to get nowhere trying to re-install analyze-css again and so I gave up and ran the server anyway to see what would happen. 

At least it's "working".

Anyway, unless there's something I don't understand, the main issue I can see now is that the results between the private instance and the public facing instance are sometimes similar-ish but not the same. Also different results when running the same website on the private instance.

Here's the results from public facing YT site: https://i.imgur.com/La2ba2D.jpg
here's the results from our private instance: https://i.imgur.com/E9Z1Td2.jpg

I'd expect some minor discrepancies with execution times and things of that nature, but not things like **DOM Elements Count**, or **Complex CSS Selectors** which are wildly different (as are some other things).

**Comment by ozcoder** [comment]
@mikeott You should download the shell script from https://deb.nodesource.com/setup_16.x (or preferably version 18.x) and double check that the code isn't doing anything dodgy. Then run it to install Node. Most Linux distro's are far behind on Node versions. See https://github.com/nodejs/release#release-schedule
